spring:
  application:
    name: ucamp-api

  datasource:
    url: jdbc:postgresql://localhost:5432/ucamp
    username: postgres
    password: dn0513

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secret: "THIS_IS_SUPER_LONG_SECRET_0123456789abcdef0123456789abcdef"
  access-token-exp-minutes: 60

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.tool.schema: debug
